<a href="https://colab.research.google.com/github/Santjee/AssimentTest1/blob/main/NumpPW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
l1 = [1,2,3,4]
arr = np.array(l1)

In [4]:
print(arr)

[1 2 3 4]


In [11]:
type(arr)

numpy.ndarray

In [14]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.asarray(l1)

array([1, 2, 3, 4])

In [16]:
a=[1,2,3,4]

In [17]:
np.asarray(a)

array([1, 2, 3, 4])

In [18]:
b = np.matrix(a)

In [19]:
b

matrix([[1, 2, 3, 4]])

In [20]:
np.asarray(b)

array([[1, 2, 3, 4]])

In [21]:
a = np.array(l1)

In [22]:
a

array([1, 2, 3, 4])

In [23]:
c = a

In [24]:
c

array([1, 2, 3, 4])

In [25]:
a

array([1, 2, 3, 4])

In [27]:
c[0] = 100

In [28]:
c

array([100,   2,   3,   4])

In [29]:
a

array([100,   2,   3,   4])

In [31]:
d = np.copy(a)

In [32]:
d

array([100,   2,   3,   4])

In [33]:
a

array([100,   2,   3,   4])

In [34]:
a[1] = 200

In [35]:
a

array([100, 200,   3,   4])

In [36]:
d

array([100,   2,   3,   4])

In [40]:
np.fromfunction(lambda x,y:x==y , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [41]:
np.fromfunction(lambda x,y:x*y , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [42]:
# @title Default title text
np.fromfunction(lambda x,y:x+y , (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [43]:
iterable = (i*i for i in range(5))

In [45]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
np.fromstring('1,2,3', sep=',')

array([1., 2., 3.])

In [49]:
np.fromstring('1 2 3', sep=' ')

array([1., 2., 3.])

In [50]:
arr.ndim # array shape

1

In [51]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [52]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2.ndim

2

In [55]:
arr2.shape

(2, 3)

In [56]:
arr2.size

6

In [57]:
arr2.dtype

dtype('int64')

In [58]:
range(10)

range(0, 10)

In [59]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
np.arange(2.3,10.6,0.5)

array([ 2.3,  2.8,  3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,
        7.8,  8.3,  8.8,  9.3,  9.8, 10.3])

In [62]:
list(np.arange(2.3,10.6,0.5))

[2.3,
 2.8,
 3.3,
 3.8,
 4.3,
 4.8,
 5.3,
 5.8,
 6.3,
 6.8,
 7.3,
 7.8,
 8.3,
 8.8,
 9.3,
 9.8,
 10.3]

In [63]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
arr3 = np.zeros((2,5,3))

In [68]:
arr3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [69]:
arr3.ndim

3

In [71]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
on =np.ones((2,5,3))

In [80]:
on +5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [81]:
on*2

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [82]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [84]:
np.empty((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [89]:
np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [90]:
np.logspace(1,10,5,base=2)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [91]:
np.random.rand(5)

array([0.12073588, 0.34143955, 0.77211599, 0.68552153, 0.82932602])

In [93]:
arr = np.random.randn(3,4)

In [94]:
import pandas as pd

In [95]:
pd.DataFrame(arr)

0         1         2         3
0 -0.379878  0.520860  0.916081  0.944931
1 -1.468700 -0.676156  1.104805  0.721517
2  0.837120 -1.330530 -0.889168  0.990138

In [96]:
np.random.rand(3,4)

array([[0.85399901, 0.67305045, 0.54675206, 0.8508174 ],
       [0.73580092, 0.74132562, 0.76845855, 0.70078237],
       [0.27502852, 0.5110302 , 0.53578359, 0.30167505]])

In [98]:
np.random.randint(1,101,(3,4))

array([[50, 16, 62, 23],
       [62, 14, 23,  1],
       [60, 54, 14, 25]])

In [102]:
pd.DataFrame(np.random.randint(1,101,(30,4)))

AttributeError: module 'pandas' has no attribute 'to_csv'

In [103]:
pd.DataFrame(np.random.randint(1,101,(30,4))).to_csv('test.csv')

In [104]:
arr = np.random.rand(3,4)

In [106]:
arr

array([[0.70351167, 0.34283336, 0.45729056, 0.69316664],
       [0.34393247, 0.1964821 , 0.72962724, 0.2159664 ],
       [0.15951542, 0.86206274, 0.44338764, 0.86343745]])

In [113]:
arr1 = arr.reshape(6,2)

In [114]:
arr1

array([[0.70351167, 0.34283336],
       [0.45729056, 0.69316664],
       [0.34393247, 0.1964821 ],
       [0.72962724, 0.2159664 ],
       [0.15951542, 0.86206274],
       [0.44338764, 0.86343745]])

In [115]:
arr1[1][1]

0.6931666412596744

In [117]:
arr1[2:5,1]

array([0.1964821 , 0.2159664 , 0.86206274])

In [123]:
arr = np.random.randint(1,101,(4,4))

In [119]:
arr

array([[ 28,  28,  38,  90],
       [ 14,  54,  71,  82],
       [ 60, 100,  29,  46]])

In [120]:
arr>50

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False]])

In [121]:
arr[arr>50]

array([ 90,  54,  71,  82,  60, 100])

In [124]:
arr

array([[ 58,  17,   1,  84],
       [ 53,   6,  62,  80],
       [ 72,  52, 100,  21],
       [ 58,  58,  95,  72]])

In [126]:
arr[2:4,1:3]

array([[ 52, 100],
       [ 58,  95]])

In [128]:
arr[0][0]  = 1000

In [129]:
arr

array([[1000,   17,    1,   84],
       [  53,    6,   62,   80],
       [  72,   52,  100,   21],
       [  58,   58,   95,   72]])

In [134]:
arr1 = np.random.randint(1,4,(4,4))
arr2 = np.random.randint(1,4,(4,4))

In [131]:
arr1

array([[3, 1, 2, 2],
       [2, 2, 3, 3],
       [3, 3, 1, 2],
       [1, 2, 3, 2]])

In [135]:
arr2

array([[3, 3, 1, 1],
       [2, 2, 2, 3],
       [1, 2, 3, 2],
       [3, 2, 3, 1]])

In [136]:
arr1 + arr2

array([[5, 6, 2, 2],
       [4, 3, 3, 6],
       [2, 3, 6, 3],
       [5, 5, 4, 4]])

In [137]:
arr1-arr2

array([[-1,  0,  0,  0],
       [ 0, -1, -1,  0],
       [ 0, -1,  0, -1],
       [-1,  1, -2,  2]])

In [138]:
arr1/arr2

array([[0.66666667, 1.        , 1.        , 1.        ],
       [1.        , 0.5       , 0.5       , 1.        ],
       [1.        , 0.5       , 1.        , 0.5       ],
       [0.66666667, 1.5       , 0.33333333, 3.        ]])

In [139]:
arr1*arr2

array([[6, 9, 1, 1],
       [4, 2, 2, 9],
       [1, 2, 9, 2],
       [6, 6, 3, 3]])

In [140]:
arr1

array([[2, 3, 1, 1],
       [2, 1, 1, 3],
       [1, 1, 3, 1],
       [2, 3, 1, 3]])

In [141]:
arr2

array([[3, 3, 1, 1],
       [2, 2, 2, 3],
       [1, 2, 3, 2],
       [3, 2, 3, 1]])

In [142]:
arr1@arr2

array([[16, 16, 14, 14],
       [18, 16, 16, 10],
       [11, 13, 15, 11],
       [22, 20, 20, 16]])

In [143]:
arr1/0

<ipython-input-143-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [144]:
arr1+100

array([[102, 103, 101, 101],
       [102, 101, 101, 103],
       [101, 101, 103, 101],
       [102, 103, 101, 103]])

In [145]:
arr1**2

array([[4, 9, 1, 1],
       [4, 1, 1, 9],
       [1, 1, 9, 1],
       [4, 9, 1, 9]])

In [146]:
#Numpy - Broadcasting.

In [147]:
arr = np.zeros((4,4))

In [148]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
row = np.array([1,2,3,4])

In [150]:
row

array([1, 2, 3, 4])

In [151]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [152]:
row.T

array([1, 2, 3, 4])

In [153]:
col = np.array([[1,2,3,4]])

In [155]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [156]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
arr1 = np.random.randint(1,4,(3,4))

In [159]:
arr1

array([[2, 1, 3, 2],
       [2, 1, 2, 2],
       [3, 1, 3, 3]])

In [160]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.73205081, 1.41421356],
       [1.41421356, 1.        , 1.41421356, 1.41421356],
       [1.73205081, 1.        , 1.73205081, 1.73205081]])

In [161]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183, 20.08553692,  7.3890561 ],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  7.3890561 ],
       [20.08553692,  2.71828183, 20.08553692, 20.08553692]])

In [162]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.47712125, 0.30103   ],
       [0.30103   , 0.        , 0.30103   , 0.30103   ],
       [0.47712125, 0.        , 0.47712125, 0.47712125]])